Feature branch
RichardBongani/Newsweek.com pull request #1
Opened 2019-10-18 19:02 UTC by RichardBongani

2019-11-28 19:15 UTC, Anna-Myzukina commented
### Pull Request under the review by Anna Muzykina (TSE)

2019-11-28 19:36 UTC, Anna-Myzukina commented
### Hi Richard!

### Nice job! Project looks! :+1: 

### But first of all let's fix the next problems and we can move on.
* Fix problems with linter now it`s not working :(

* Kindly recommended checking HTML markup with this [validator](https://validator.w3.org/#validate_by_upload)

Now it shows a lot of ERRORs in your project

![Screenshot from 2019-11-28 21-27-38](https://user-images.githubusercontent.com/26605804/69828797-fdd66e80-1225-11ea-93f4-05793e05ddb6.png)


* Your README.md file should be descriptive, I hope this short [Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) can help you to make this file.

Now you readme file without any descriptions

![reedme](https://user-images.githubusercontent.com/26605804/69828830-2199b480-1226-11ea-96fc-41f81724b12a.png)

* Please check responsiveness of your project, as I can see all parts have problems :(

For example :

![3humu2](https://user-images.githubusercontent.com/26605804/69828965-b3a1bd00-1226-11ea-81f9-f5a1c9783dd6.gif)



-----------------------------------------

Please remember that your branch name should be descriptive (e.g., refactor-authentication, user-content-cache-key, make-retina-avatars), so that others can see what is being worked on. You can read more about it [here](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/). I hope in the next project you can do this!


### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*

*Happy coding 😄*

2019-11-28 19:37 UTC, Anna-Myzukina reviewed
The project needs changes.

2019-11-28 19:39 UTC, Anna-Myzukina requested changes
Linter does not work correctly. The HTML file has errors, readme file is not descriptive. The project isn`t responsive.

2019-11-28 22:18 UTC, RichardBongani commented
> The project needs changes.

Awesome, thank you Anna. Working on it.

2019-12-18 18:51 UTC, Anna-Myzukina commented
### Hi Richard!

### Great job!  :+1: 

But your project still needs changes

* Please check problems with linter now it shows errors, kindly recommended fix it :(
Follow this link to see errors: [Details](https://github.com/RichardBongani/Newsweek.com/pull/1/checks?check_run_id=354981141)


![linter](https://user-images.githubusercontent.com/26605804/71113742-ed873300-21d6-11ea-8cc5-ad33afb78f9e.png)

* Kindly recommended checking HTML markup with this [validator](https://validator.w3.org/#validate_by_upload)

![screen](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/validation_requirement.png)
It shows a lot of ERRORs in your project

![validator](https://user-images.githubusercontent.com/26605804/71114213-f9272980-21d7-11ea-8003-a092835e504b.png)

* Please check responsiveness of your project, as I can see all parts have problems :(

### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*

*Happy coding 😄*

2019-12-18 18:54 UTC, Anna-Myzukina commented on index.html
> +            <button type="button" name="sign-up" class="sign-newsletter">SIGN UP ></button>
Line number 472: Special characters must be escaped : [ > ].

2019-12-18 18:55 UTC, Anna-Myzukina commented on index.html
> +    </div>
Line number 478: Tag must be paired, no start tag: [ </div> ]

2019-12-18 18:56 UTC, Anna-Myzukina commented on index.html
> +          </div>
Line number 493: Special characters must be escaped : [ > ].

2019-12-18 18:57 UTC, Anna-Myzukina commented on index.html
> +            <P class="recession"><a href="#" class="pic-link">How to Survive a Recession: 12 Steps You Should Take to
Line number 507: The html element name of [ P ] must be in lowercase.

2019-12-18 18:57 UTC, Anna-Myzukina commented on index.html
> +            <P class="jim"><a href="#" class="pic-link">Does Jim Mattis Have a Duty to Criticize Donald Trump?</a></p>
Line number 515: The html element name of [ P ] must be in lowercase.

2019-12-18 18:58 UTC, Anna-Myzukina commented on index.html
> +                        <button type="button" name="subscribe" class="my_sub all1">SUBSCRIBE ></button>
Line number 1050: Special characters must be escaped : [ > ].

2019-12-18 18:58 UTC, Anna-Myzukina commented on index.html
> +                      <button class="sign-btn" type="button" name="btn">SIGN UP ></button>
Line number 1070: Special characters must be escaped : [ > ].

2019-12-18 19:01 UTC, Anna-Myzukina requested changes
The project still needs changes

2019-12-18 21:11 UTC, pelzolga123 requested changes
Project is not responsive, pull request requires description.

2019-12-18 21:12 UTC, pelzolga123 commented
## Hi Richard! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
### You did a good job fixing linter errors :+1: , but you didn't make all changes required previously.
 * [ ] Tablet mode of your project should look like original one. [Link to page.](https://www.newsweek.com/) Right now it looks like this:
![image](https://user-images.githubusercontent.com/20416431/71122840-267cd300-21ea-11ea-9d77-7aa8e47358e0.png)
 
Original:
![image](https://user-images.githubusercontent.com/20416431/71122986-69d74180-21ea-11ea-90aa-17d62485fa68.png)

* [ ] Mobile mode is not looking like an original one too:
![image](https://user-images.githubusercontent.com/20416431/71123174-c175ad00-21ea-11ea-94f8-ab206ed56aef.png)

Original:
![image](https://user-images.githubusercontent.com/20416431/71123231-e23e0280-21ea-11ea-8976-33e5f6f106ee.png)

* [ ] Don't forget to add description for pull request of  changes you implemented, so that your project could look more professional. [Link to screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png)

2019-12-18 22:57 UTC, pelzolga123 requested changes
Requires changes.

2019-12-18 22:57 UTC, pelzolga123 commented
### You made an attempt, but still all changes, required previously need to be done. 
* You tried to fix tablet mode responsiveness, but it still looks not good:
![image](https://user-images.githubusercontent.com/20416431/71130198-0a812d80-21fa-11ea-84b1-41f68aa343e1.png)

* You also have stickler error now, that needs fixing.

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

2019-12-19 18:54 UTC, nikasulo requested changes
# Great work so far @RichardBongani! 
Your site is going to be really great :rocket:. Please look deeply into your mobile styling, especially the tablet mode, the page isn't responding like it should to different screen sizes.

When you fix this, please submit for a re-review!

2019-12-19 22:05 UTC, nikasulo requested changes
# Hello @RichardBongani!
Your responsiveness is still a bit jagged, please look into it thoroughly. Compare what happens at each breakpoint on the original page to what happens on yours. A good way to do this might be to move sequentially through each piece/element on the page and make all appropriate change and improvements.

Try to settle down and make sure everything is in order so you don't keep going back and forth on reviews. All the best! :rocket:

2019-12-21 04:53 UTC, izaiasneto4 commented
### Hi @RichardBongani :wave: 

Nice work implementing some of the features, we're almost there :muscle: Let's make a list of the things that o need to finish before re-submitting for code review :arrow_down: 

- [ ]  Your header is still not properly adapted for the tablet/cellphone views, see the screenshot below

![image](https://user-images.githubusercontent.com/5157985/71303028-b8731000-2391-11ea-97d1-15d77ae70285.png)
Original website

![image](https://user-images.githubusercontent.com/5157985/71303030-d3de1b00-2391-11ea-85d0-ec4b2558199c.png)
Your clone
- [ ] Some of the images look too out of proportion, giving the website a not so great look. Let's fix those to make your project look better
![image](https://user-images.githubusercontent.com/5157985/71303049-30d9d100-2392-11ea-83ff-d61b41ee5d81.png)

- [ ] When resizing your project I've noticed that some sections overlap each other, let's try to fix those as well  :wink: 
![image](https://user-images.githubusercontent.com/5157985/71303086-cc6b4180-2392-11ea-82c4-8cc40f235664.png)

- [ ] Your footer is not in the right proportion for the tablet version (some of the information is overlapping and some is missing)
![image](https://user-images.githubusercontent.com/5157985/71303116-09373880-2393-11ea-9e83-fe86e224adcb.png)

- [ ] In the mobile and tablet version, your project has this big blank spaces, let's fix those as well :+1: 
![image](https://user-images.githubusercontent.com/5157985/71303139-44396c00-2393-11ea-8d65-e41211ffb39d.png)

- [ ] The "subscribe section" is out proportion and overlapping the other section in the mobile version, see screenshot
![image](https://user-images.githubusercontent.com/5157985/71303214-667fb980-2394-11ea-886b-cf1780e3070a.png)

**Please, when finished with the request, re-submit your project for a new code review**. :pray: 

**TSE: Izaias Neto**

2020-01-02 08:40 UTC, imhta approved these changes
# Project approved 🎉 

### Hello  @RichardBongani  , 👋 You have done a great job in this project 👏 

<img src="https://thumbs.gfycat.com/SpeedyAmazingIndianpalmsquirrel-size_restricted.gif">

> [Optional] fix horizontal scrolling and logo resolution, if you do clone will look great 
----
### Happy coding 😄 
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__

2020-01-06 20:59 UTC, merged